### ISSUE TITLE
API docs not working

### ISSUE THREAD

**Issue by pnrobinson** [monarch-initiative/c2p#2]
Trying to add API docs as in C2S2 project, but getting error
```
/home/runner/work/c2p/c2p/src/cp2 is not a directory.
```

**Comment by ielis** [comment]
The #4 should fix it.

**Comment by pnrobinson** [comment]
@ielis 
There is still a weird path error:
https://github.com/monarch-initiative/c2p/actions/runs/5909648087/job/16030450122

```
Building the src/c2p documentation
/home/runner/work/c2p/c2p/src/cp2 is not a directory.
```

**Comment by ielis** [comment]
Hi, yeah, computer is always right.. :blush: `cp2 != c2p`.

I also fixed some other bugs and the docs are now online at
https://monarch-initiative.github.io/c2p/stable

**Comment by pnrobinson** [comment]
I also loose when I pick fights with compilers or interpreters -- touch audience.
thanks & sorry for the mixup
